### ISSUE TITLE
Data Entry Module - Reported by McKee

### ISSUE THREAD

**Issue by ndow-user** [oss-wec/wisdm#15]
When selecting a data entry module, it is not readily apparent how the user would return to the data entry form.  The addition of a "view form" command box would help clarify how the user can return to the data entry form.

**Comment by kissmygritts** [comment]
A better method to make it clear that the x in the upper right of the module selection modal will save the module selections.

Maybe a tag? http://bulma.io/documentation/elements/tag/#combinations
