### ISSUE TITLE
Can't go directly to endpoints other than home

### ISSUE THREAD

**Issue by ndow-user** [oss-wec/wisdm#22]
Only goes to `index.html`. I don't know why, AWS S3 issue.

```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: animal-log
RequestId: D96084AF5D1F7672
HostId: 72pcHaOdI4sYUael2cUau/WjqH+AKtd6IDprQbfmTDJg/U6VXshScpkUKvKC+1hAOXNJrpeH9Rw=
```

**Comment by kissmygritts** [comment]
https://router.vuejs.org/en/essentials/history-mode.html

The fix to this issue is mentioned in the router docs.

**Comment by kissmygritts** [comment]
This article may help. We will see.
https://www.octobot.io/blog/2017-01-04-amazon-s3-and-html5-urls/

**Comment by kissmygritts** [comment]
I have fixed this by serving the app from cloudfront with a redirect to the home page on errors.
